### PR TITLE
fixed dialog problem

### LINKED ISSUE #113: dialog not shown before navigating & after adding post in addPost.dart
**Describe the bug**
dialog not shown before navigating & after adding post in addPost.dart

**To Reproduce**
1. Go to 'add post from the floating button'
2. fill some random things
3. Click on 'add post'
4. See error( it waits for 3 seconds and navigates to homepage the dialog is not shown)

**Expected behavior**
the dialog should be shown for 3 secs and then navigate to home page

### PR DESCRIPTION
**Pull request by navinkumar-k-015**
# Description

Please include the summary of the change as well as the issue that is fixed (if applicable). Also if any dependencies that are required for this change to work.

Fixes #113 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
I added another column widget and put form widget under it as the form is a type of builder so the button widget must be brought outside so that when it taps it creates a dialog and I also removed sleep and added future.delayed to make the widget disappear and route to the homepage.

# How Has This Been Tested?

- [x] Test A: checked through my emulator.

- [x] Test C: Test through flutter test code

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ok] My code follows the style guidelines of this application
- [ ok] I have checked the code working on my emulator
- [ ok] I have commented my code for better understanding
- [ ok] These changes generate no new warnings
- [ ok] These changes do not effect the existing functionalities,

### CODE REVIEW

**Comment by hayat-tamboli** [comment]
@navinkumar-k-015 please run `flutter format .` to format the document and commit to `navinkumar-k-015:new_branch`  branch

**Comment by navinkumar-k-015** [comment]
All review issues are fixed pls look into it

**Comment by navinkumar-k-015** [comment]
Can you pls merge it and label it as hacktober-fest accepted after checking everything is fine.

**Review by hayat-tamboli — APPROVED** [review]
@navinkumar-k-015 great job, do star this repo if you liked it😁.

**Comment by Manas1820** [comment]
@navinkumar-k-015 great job!

**Pull request merged**
