### PR TITLE
Completed Ui for 2 pages

### PR DESCRIPTION
**Pull request by hayat-tamboli**
* second page
image

* Login Page
image

### CODE REVIEW

**Review by Manas1820 — CHANGES_REQUESTED** [review]
> I suggest moving the forgot password to the right side instead of the left side as its standard.
> And I also suggest to once again review the sign in and sign in through google button size(It's looking a bit odd).

**Comment by mohitreddy03** [comment]
Remove the dots on 'welcome'?
The rest looks greatt

**Comment by hayat-tamboli** [comment]
## change in login page
image

**Comment by mohitreddy03** [comment]
Let both the buttons be of equal size
Probably compromise on th font

**Comment by hayat-tamboli** [comment]
> Let both the buttons be of equal size
> Probably compromise on the font size

bad idea,
we should have uniform font sizes in all buttons

**Comment by Manas1820** [comment]
Amazing Design Looks cool now

**Comment by sbangariGIT** [comment]
Great work!!

**Pull request merged**
