### PR TITLE
Added Dark Mode Switch

### PR DESCRIPTION
**Pull request by sainiteshb**
# Description

I have added the dark mode switch to the app.
I have added two dependencies 
* provider:
*fontawesome_icons_flutter:

Fixes # (issue)

## Type of change

Dark Mode

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Also, summarise the process for us to reproduce.

- [yes ] Test A: checked through my emulator.
- [ yes] TestB: Test through flutter test code

# Checklist:

- [ *] My code follows the style guidelines of this application
- [ *] I have checked the code working on my emulator
- [ *] I have commented my code for better understanding
- [ *] These changes generate no new warnings
- [ *] These changes do not effect the existing functionalities, 

Screenshot_1602083920 
Screenshot_1602083989
Screenshot_1602084211

### CODE REVIEW

**Comment by hayat-tamboli** [comment]
#### comment out that local variable theme in the profile page and you will be good to go
image

**Comment by sainiteshb** [comment]
yes i have updated the code

**Review by hayat-tamboli — APPROVED** [review]
Awesome job🔥

**Comment by sainiteshb** [comment]
Thank you 😊

**Comment by Manas1820** [comment]
Nice Job @sainiteshb

**Comment by sainiteshb** [comment]
@Manas1820  thank you so  much

**Pull request merged**
